version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: carrental
      MYSQL_USER: caruser
      MYSQL_PASSWORD: carpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
