name: Deploy to Servers

on:
  push:
    branches:
      - staging
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          ssh ubuntu@44.211.194.84 << EOF
            cd carport && git pull origin staging
            docker-compose up -d --build
          EOF

      - name: Deploy to Production
        if: github.ref == 'refs/heads/deployment'
        run: |
          ssh ubuntu@18.209.167.66 << EOF
            cd carport && git pull origin deployment
            docker-compose up -d --build
          EOF
