name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli php-mysql unzip wget curl jq
          sudo apt-get install -y python3-pip
          pip install selenium webdriver-manager

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          wget -O chromedriver.zip $(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver

      - name: Start PHP Server
        run: |
          php -S 127.0.0.1:8000 -t ${{ github.workspace }} > server.log 2>&1 &
          sleep 15  # Give the server time to start

      - name: Check If Server is Running
        run: |
          curl -I http://127.0.0.1:8000 || (cat server.log && exit 1)

      - name: Run Selenium Test
        run: python3 test_car_rental.py
